Attribute VB_Name = "CTest"
Attribute VB_Base = "0{FCFB3D2A-A0FA-1068-A738-08002B3371B5}"
Attribute VB_GlobalNameSpace = False
Attribute VB_Creatable = True
Attribute VB_PredeclaredId = False
Attribute VB_Exposed = True
Attribute VB_TemplateDerived = False
Attribute VB_Customizable = False
Option Explicit

'5-MultiUse，那么别的文件中的VBA项目也可使用这个类
'VBE.ActiveVBProject.VBComponents("ClassName").Properties("Instancing") = 5

Public Sub Test()
    MsgBox "test class"
End Sub